In [61]:
import pandas as pd 
import numpy as np 
import os
import torch

# Deep Neural Networks Laboratory

## Set up Pytorch

Install the Pytorch library from https://pytorch.org/get-started/locally/ (depending on your machine)

If your machine has a Nvidia GPU, consider installing the CUDA version of Pytorch (also available on the previous link)

You can check the installation by doing:

In [62]:
torch.__version__

'2.1.2'

To check if the CUDA version of Pytorch was installed successfully, only if your machine supports CUDA, you can do:

In [63]:
torch.cuda.is_available()

False

## Tensors

Tensors are the building blocks of Pytorch models. They are multi-dimensional arrays of numerical values.

You can think of Tensors as generalized vectors.

![images/tensor.png](images/tensor.png) 

A tensor can be defined directly from python arrays or numpy vectors.

In [64]:
tensor_1 = torch.tensor( [ [1,2,3,4,5],[1,2,3,4,5] ])
tensor_1

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [65]:
np_tensor = np.array( [ [1,2,3,4,5],[1,2,3,4,5] ])
tensor_2 = torch.from_numpy(np_tensor)
tensor_2

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

You can check the equivalence of two tensors, item by item.

In [66]:
tensor_1.eq(tensor_2)

tensor([[True, True, True, True, True],
        [True, True, True, True, True]])

You can also convert the tensors back to list or Numpy.

In [67]:
tensor_1.numpy()

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [68]:
tensor_1.tolist()

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

You can initialize tensors in a variety of ways. 

You can instantiate tensors full of 0s, of 1s, of random numbers, etc...

You can refer to the Pytorch Documentation for more info. https://pytorch.org/docs/stable/index.html

In [69]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5031, 0.0680, 0.1246],
        [0.2398, 0.2272, 0.8301]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


There are three main attributes that each tensor is defined by:
1. Its shape;
2. The type of its elements;
3. The device containint the tensor.

In [70]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


By default, tensors are created on the cpu. However, you can move them to another if needed.

In [71]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

tensor.device

device(type='cpu')

In [72]:
tensor

tensor([[0.5715, 0.9744, 0.6788, 0.7152],
        [0.7047, 0.3291, 0.2576, 0.5234],
        [0.9866, 0.2811, 0.1542, 0.3521]])

In [73]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")

First row: tensor([0.5715, 0.9744, 0.6788, 0.7152])
First column: tensor([0.5715, 0.7047, 0.9866])
Last column: tensor([0.7152, 0.5234, 0.3521])


### Concatenating or Stacking Tensors

In [74]:
tensor = torch.tensor( [1,2,3,4,5])
tensor

tensor([1, 2, 3, 4, 5])

In [75]:
torch.cat([tensor,tensor],dim=0)

tensor([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [76]:
torch.stack([tensor,tensor],dim=0)

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [77]:
torch.stack([tensor,tensor], dim=1)

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]])

## Operations on tensors

In [78]:
tensor = torch.tensor( [ [1,2,3],[4,5,6],[7,8,9] ], dtype=torch.float32)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

.T transposes the tensor.

In [79]:
tensor.T

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])

@ computes the matrix multiplication.

In [80]:
tensor @ tensor

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [81]:
tensor.matmul(tensor)

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

* computes the element-wise multiplication.

In [82]:
tensor * tensor

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

We can compute several statistics on a tensor.

In [83]:
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [84]:
torch.mean(tensor)

tensor(5.)

In [85]:
torch.mean(tensor,dim=0)

tensor([4., 5., 6.])

In [86]:
torch.mean(tensor,dim=1)

tensor([2., 5., 8.])

In [87]:
torch.std(tensor)

tensor(2.7386)

Thanks for reading this far \(: 