In [1]:
import pandas as pd 
import numpy as np 
import os
import torch

# Deep Neural Networks Laboratory

## Set up Pytorch

Install the Pytorch library from https://pytorch.org/get-started/locally/ (depending on your machine)

If your machine has a Nvidia GPU, consider installing the CUDA version of Pytorch (also available on the previous link)

You can check the installation by doing:

In [2]:
torch.__version__

'2.2.0'

To check if the CUDA version of Pytorch was installed successfully, only if your machine supports CUDA, you can do:

In [3]:
torch.cuda.is_available()

True

## Tensors

Tensors are the building blocks of Pytorch models. They are multi-dimensional arrays of numerical values.

You can think of Tensors as generalized vectors.

![images/tensor.png](images/tensor.png) 

A tensor can be defined directly from python arrays or numpy vectors.

In [4]:
tensor_1 = torch.tensor( [ [1,2,3,4,5],[1,2,3,4,5] ])
tensor_1

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [5]:
np_tensor = np.array( [ [1,2,3,4,5],[1,2,3,4,5] ])
tensor_2 = torch.from_numpy(np_tensor)
tensor_2

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]], dtype=torch.int32)

You can check the equivalence of two tensors, item by item.

In [6]:
tensor_1.eq(tensor_2)

tensor([[True, True, True, True, True],
        [True, True, True, True, True]])

You can also convert the tensors back to list or Numpy.

In [7]:
tensor_1.numpy()

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]], dtype=int64)

In [8]:
tensor_1.tolist()

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

You can initialize tensors in a variety of ways. 

You can instantiate tensors full of 0s, of 1s, of random numbers, etc...

You can refer to the Pytorch Documentation for more info. https://pytorch.org/docs/stable/index.html

In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1250, 0.9579, 0.9384],
        [0.9773, 0.5934, 0.3981]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


There are three main attributes that each tensor is defined by:
1. Its shape;
2. The type of its elements;
3. The device containint the tensor.

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


By default, tensors are created on the cpu. However, you can move them to another if needed.

In [11]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

tensor.device

device(type='cuda', index=0)

In [12]:
tensor

tensor([[0.7345, 0.2648, 0.1289, 0.9290],
        [0.9959, 0.9770, 0.7195, 0.3898],
        [0.7249, 0.2067, 0.7487, 0.3668]], device='cuda:0')

In [13]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")

First row: tensor([0.7345, 0.2648, 0.1289, 0.9290], device='cuda:0')
First column: tensor([0.7345, 0.9959, 0.7249], device='cuda:0')
Last column: tensor([0.9290, 0.3898, 0.3668], device='cuda:0')


### Concatenating or Stacking Tensors

In [14]:
tensor = torch.tensor( [1,2,3,4,5])
tensor

tensor([1, 2, 3, 4, 5])

In [15]:
torch.cat([tensor,tensor],dim=0)

tensor([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [16]:
torch.stack([tensor,tensor],dim=0)

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [17]:
torch.stack([tensor,tensor], dim=1)

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]])

## Operations on tensors

In [18]:
tensor = torch.tensor( [ [1,2,3],[4,5,6],[7,8,9] ], dtype=torch.float32)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

.T transposes the tensor.

In [19]:
tensor.T

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])

@ computes the matrix multiplication.

In [20]:
tensor @ tensor

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [21]:
tensor.matmul(tensor)

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

* computes the element-wise multiplication.

In [22]:
tensor * tensor

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

We can compute several statistics on a tensor.

In [23]:
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [24]:
torch.mean(tensor)

tensor(5.)

In [25]:
torch.mean(tensor,dim=0)

tensor([4., 5., 6.])

In [26]:
torch.mean(tensor,dim=1)

tensor([2., 5., 8.])

In [27]:
torch.std(tensor)

tensor(2.7386)

This is the end of our first notebook (: